Updated test aperture yml file

diff --git a/.github/workflows/test-aperture.yml b/.github/workflows/test-aperture.yml
--- a/.github/workflows/test-aperture.yml
+++ b/.github/workflows/test-aperture.yml
@@ -31,36 +31,36 @@ jobs:
           comment-id: ${{ github.event.comment.id }}
           reactions: eyes
 
-      - name: Validate pull request
-        uses: actions/github-script@v6
-        id: pr_data
-        env:
-          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
-        with:
-          script: |
-            try {
-              const pullRequest = await github.rest.pulls.get({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                pull_number: context.issue.number,
-              });
+      # - name: Validate pull request
+      #   uses: actions/github-script@v6
+      #   id: pr_data
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
+      #   with:
+      #     script: |
+      #       try {
+      #         const pullRequest = await github.rest.pulls.get({
+      #           owner: context.repo.owner,
+      #           repo: context.repo.repo,
+      #           pull_number: context.issue.number,
+      #         });
 
-              // Pull request from fork
-              if (context.payload.repository.full_name !== pullRequest.data.head.repo.full_name) {
-                const errorMessage = '`/test-aperture` is not supported on pull requests from forked repositories.';
+      #         // Pull request from fork
+      #         if (context.payload.repository.full_name !== pullRequest.data.head.repo.full_name) {
+      #           const errorMessage = '`/test-aperture` is not supported on pull requests from forked repositories.';
 
-                await github.rest.issues.createComment({
-                  issue_number: context.issue.number,
-                  owner: context.repo.owner,
-                  repo: context.repo.repo,
-                  body: errorMessage,
-                });
+      #           await github.rest.issues.createComment({
+      #             issue_number: context.issue.number,
+      #             owner: context.repo.owner,
+      #             repo: context.repo.repo,
+      #             body: errorMessage,
+      #           });
 
-                core.setFailed(errorMessage);
-              }
-            } catch (err) {
-              core.setFailed(`Request failed with error ${err}`);
-            }
+      #           core.setFailed(errorMessage);
+      #         }
+      #       } catch (err) {
+      #         core.setFailed(`Request failed with error ${err}`);
+      #       }
 
       - name: Add link to build
         uses: actions/github-script@v6
@@ -122,19 +122,19 @@ jobs:
         with:
           script-name: "build"
 
-      - name: Get Markdown Changeset Files Difference
-        id: diff_changeset_files
-        run: |
-            git fetch origin ${{ steps.comment-branch.outputs.base_ref }}
-            git diff --name-only origin/${{ steps.comment-branch.outputs.base_ref }}...HEAD .changeset/*.md > changeset_diff.txt
+      # - name: Get Markdown Changeset Files Difference
+      #   id: diff_changeset_files
+      #   run: |
+      #       git fetch origin ${{ steps.comment-branch.outputs.base_ref }}
+      #       git diff --name-only origin/${{ steps.comment-branch.outputs.base_ref }}...HEAD .changeset/*.md > changeset_diff.txt
 
-      - name: Delete Unrelated Markdown Files in Changeset
-        run: |
-            for file in $(ls .changeset/*.md); do
-              if ! grep -q "$(basename $file)" changeset_diff.txt; then
-                rm "$file"
-              fi
-            done
+      # - name: Delete Unrelated Markdown Files in Changeset
+      #   run: |
+      #       for file in $(ls .changeset/*.md); do
+      #         if ! grep -q "$(basename $file)" changeset_diff.txt; then
+      #           rm "$file"
+      #         fi
+      #       done
 
       - name: Create and publish snapshot release and trigger aperture
         uses: actions/github-script@v6
