ci(pie-monorepo): [Changed] Recombine Amplify build and deploy jobs

diff --git a/.github/actions/amplify-deploy/action.yml b/.github/actions/amplify-deploy/action.yml
--- a/.github/actions/amplify-deploy/action.yml
+++ b/.github/actions/amplify-deploy/action.yml
@@ -27,24 +27,46 @@ inputs:
 runs:
   using: composite
   steps:
-  # Download Github artifact
-  # - name: Download artifact
-  #   id: download-artifact
-  #   uses: actions/download-artifact@v3
-  #   with:
-  #     name: '${{ inputs.package-name }}-pr-${{github.event.number}}.zip'
-  # Deploy Amplify
-  # - name: Deploy Amplify from Github
-  #   shell: bash
-  #   run: |
-  #     aws amplify start-deployment \
-  #       --app-id ${{ inputs.amplify-app-id }} \
-  #       --branch-name ${{ inputs.branch-name }} \
-  #       --source-url fileb://./${{ inputs.package-name }}-pr-${{github.event.number}}.zip
-  #   env:
-  #     AWS_REGION: ${{ inputs.aws-region }}
-  #     AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
-  #     AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
+  # Zip dist folder
+  - name: Zip build output
+    shell: bash
+    run: |
+      cd apps/${{ inputs.package-name }}/dist
+      zip -r ../../../${{ inputs.package-name }}-pr-${{github.event.number}}.zip .
+  # Upload zip as Github Action artifact
+  - name: Upload artifact to Github
+    id: upload-github
+    uses: actions/upload-artifact@v3
+    with:
+      name: ${{ inputs.package-name }}-pr-${{github.event.number}}.zip
+      path: ${{ inputs.package-name }}-pr-${{github.event.number}}.zip
+      retention-days: 7
+  # Upload zip to S3
+  - name: Upload to S3
+    id: upload-s3
+    uses: hkusu/s3-upload-action@v2
+    with:
+      aws-access-key-id: ${{ inputs.aws-access-key-id }}
+      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
+      aws-region: ${{ inputs.aws-region }}
+      aws-bucket: ${{ inputs.bucket-name }}
+      bucket-root: '/'
+      destination-dir: '/'
+      file-path: './${{ inputs.package-name }}-pr-${{github.event.number}}.zip'
+      content-type: 'application/zip'
+  # Create branch on Amplify
+  - name: Create Amplify branch
+    shell: bash
+    # We return true to prevent the step from failing if the branch already exists
+    run: |
+      aws amplify create-branch \
+        --app-id ${{ inputs.amplify-app-id }} \
+        --branch-name ${{ inputs.branch-name }} \
+        || true
+    env:
+      AWS_REGION: ${{ inputs.aws-region }}
+      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
+      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
   # Deploy Amplify from S3
   - name: Deploy Amplify from S3
     shell: bash
