ci(pie-monorepo): [Changed] Change order of build jobs

diff --git a/.github/actions/amplify-deploy/action.yml b/.github/actions/amplify-deploy/action.yml
--- a/.github/actions/amplify-deploy/action.yml
+++ b/.github/actions/amplify-deploy/action.yml
@@ -40,6 +40,30 @@ runs:
       name: ${{ inputs.package-name }}-pr-${{github.event.number}}
       path: ${{ inputs.package-name }}-pr-${{github.event.number}}.zip
       retention-days: 7
+  - name: Upload S3
+    uses: hkusu/s3-upload-action@v2
+    with:
+      aws-access-key-id: ${{ inputs.aws-access-key-id }}
+      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
+      aws-region: '${{ inputs.aws-region }}'
+      aws-bucket: ${{ inputs.bucket-name }}
+      bucket-root: '/'
+      destination-dir: '/'
+      file-path: './${{ inputs.package-name }}-pr-${{github.event.number}}.zip'
+      content-type: 'application/zip'
+  - name: Create Amplify branch
+    shell: bash
+    # We return true to prevent the step from failing if the branch already exists
+    run: |
+      aws amplify create-branch \
+        --app-id ${{ inputs.amplify-app-id }} \
+        --branch-name ${{ inputs.branch-name }} \
+        || true
+    env:
+      AWS_REGION: ${{ inputs.aws-region }}
+      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
+      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
+  # List workflow artifacts
   - name: List workflow artifacts
     id: list-artifacts
     uses: actions/github-script@v6
@@ -54,29 +78,6 @@ runs:
         console.log('Artifact names', artifacts.artifacts.map(x => x.name));
         const distArtifact = artifacts.artifacts.find(artifact => artifact.name === '${{ inputs.package-name }}-pr-${{github.event.number}}');
         return { distArtifactUrl: distArtifact.archive_download_url };
-  # - name: Upload S3
-  #   uses: hkusu/s3-upload-action@v2
-  #   with:
-  #     aws-access-key-id: ${{ inputs.aws-access-key-id }}
-  #     aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
-  #     aws-region: '${{ inputs.aws-region }}'
-  #     aws-bucket: ${{ inputs.bucket-name }}
-  #     bucket-root: '/'
-  #     destination-dir: '/'
-  #     file-path: './${{ inputs.package-name }}-pr-${{github.event.number}}.zip'
-  #     content-type: 'application/zip'
-  - name: Create Amplify branch
-    shell: bash
-    # We return true to prevent the step from failing if the branch already exists
-    run: |
-      aws amplify create-branch \
-        --app-id ${{ inputs.amplify-app-id }} \
-        --branch-name ${{ inputs.branch-name }} \
-        || true
-    env:
-      AWS_REGION: ${{ inputs.aws-region }}
-      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
-      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
   # Deploy Amplify
   - name: Deploy Amplify
     shell: bash
